name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Unit Tests

    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Calculate code coverage
        run: npm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{ matrix.os }}
          parallel: true

  notify:
    needs:
      - build

    name: Code Coverage
    if: ${{ success() }}
    runs-on: ubuntu-latest

    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

  publish:
    needs:
      - build
      - notify

    name: Publish to npm
    if: ${{ success() && github.event_name == 'push' && github.repository_owner == 'accordproject' }}
    runs-on: ubuntu-latest

    outputs:
      job-status: ${{ job.status }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - run: npm ci
      - run: npm run build --if-present

    - name: tag
        id: tag
        run: |
          node ./scripts/tag.js ${{ github.event.release.tag_name }}

      - name: build and publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm version --no-git-tag-version --yes --exact ${{ github.event.release.tag_name  }}
          npm publish --access public ${{ steps.tag.outputs.tag }} 2>&1

    - name: Create PR to increment version
        uses: peter-evans/create-pull-request@v3
        with:
          base: main
          commit-message: 'chore(actions): publish ${{ github.event.release.tag_name }} to npm'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: ap-publish-${{ github.event.release.tag_name }}
          delete-branch: true
          title: 'chore(actions): publish ${{ github.event.release.tag_name }} to npm'
          body: |
            # Increment Versions
            Update the package.json version numbers after publishing to NPM.
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          draft: false
